# Autogenerated wrapper script for xrt_jll for x86_64-linux-gnu-cxx03
export libxilinxopencl, libxrt_coreutil

using Libuuid_jll
using OpenSSL_jll
using libdrm_jll
using Ncurses_jll
using LibYAML_jll
using protobuf_c_jll
using ELFIO_jll
using ocl_icd_jll
using rapidjson_jll
using LibCURL_jll
using systemtap_jll
using systemd_jll
using Libffi_jll
JLLWrappers.@generate_wrapper_header("xrt")
JLLWrappers.@declare_library_product(libxilinxopencl, "libxilinxopencl.so.2")
JLLWrappers.@declare_library_product(libxrt_coreutil, "libxrt_coreutil.so.2")
function __init__()
    JLLWrappers.@generate_init_header(Libuuid_jll, OpenSSL_jll, libdrm_jll, Ncurses_jll, LibYAML_jll, protobuf_c_jll, ELFIO_jll, ocl_icd_jll, rapidjson_jll, LibCURL_jll, systemtap_jll, systemd_jll, Libffi_jll)
    JLLWrappers.@init_library_product(
        libxilinxopencl,
        "lib/libxilinxopencl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxrt_coreutil,
        "lib/libxrt_coreutil.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
